# Generated by Django 4.0.5 on 2022-06-06 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_peanut_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peanut',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
