# Generated by Django 4.0.5 on 2022-06-06 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_peanut_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peanut',
            name='slug',
        ),
    ]
