# Generated by Django 4.0.5 on 2022-06-07 09:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_peanut_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='peanut',
            name='image_url',
            field=models.URLField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
