# Generated by Django 4.0.5 on 2022-06-07 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_peanut_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peanut',
            name='image_url',
            field=models.URLField(max_length=250),
        ),
    ]
